# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
