# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20171005_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('firm', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(null=True)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('due', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('payment', models.CharField(max_length=10)),
            ],
        ),
    ]
