# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
